### ISSUE TITLE
Disable Country Code Function

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/radiobrowser#163]
With the country code introduced, users can’t input the country name as they want, so they have to choose a given country name from the database. Unfortunately some of the names come in full spelling instead of short form spelling, causing a new country added, which will mess the country list. For example, **South Korea** has to be **Korea (Republic of)**, **Laos** has to be **Lao People's Democratic Republic**, and users will no longer add new item to South Korea or Laos.
Radiodroid country flag display is based on current short form spelling instead of full spelling, which will also be affected by the country code function.
Country name can be a drop-down menu based on current names.

**Comment by segler-alex** [comment]
the initial reason of adding a countrycode field was to add an machine readable field for linking the station to countries. the current one is not machine readable, there are many cases where the official name deviates from the country name in the database.
i wanted to add a dependable station name, and the most dependable is the iso 2 letter country code. for a country code to be usefull i could either
a) add all the countries myself to the database from a central united nations page or
b) use an already existing service.
i choose b) because, then i don't have to change it myself according to the current country situation. and i found there are already some out there that do exactly that what i wanted.
i choose https://restcountries.eu/, it had all features and was easy to use.

to make it easy for users, i did not want to have 2 country input fields, one for the code and one for the name, people would ask why they have to add the country twice. so i made one field automatic and read only in the web ui. 
to be compatible to old users of the API i had to keep the country field for now. but i marked it as deprecated so new users would use the dependable countrycode field.

new stations are handled then automatically
existing stations needed to be added an country code which for many stations i already did, but am still on it for some.

**Comment by zo-shin** [comment]
OK, but please keep the country list simple. The country name needn’t be given in full spelling like **United Kingdom of Great Britain and Northern Ireland** or **Korea (Republic of)**, current **United Kingdom** and **South Korea** are better.
And the **country** field is not compatible with my Chrome 48-based browser. No matter what I input there, it can’t be recognized.
