### ISSUE TITLE
Station updating: "Sending..." is not cleared

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/radiobrowser#23]
![20170201-23 28 41_auswahl](https://cloud.githubusercontent.com/assets/1151915/22529079/4a389bee-e8d6-11e6-9dc5-761f1b52eeb8.png)

**Comment by indr** [comment]
Server responds with some invalid output.

![image](https://cloud.githubusercontent.com/assets/849548/24752751/dcf22bd2-1b01-11e7-8fd7-3a2fa2342ce2.png)

Also, in case of an error the `vm.activeSending` is not set to false therefore the modal never closes. Would be nice to have some sort of error message.

@segler-alex Could you please have a look into this as it makes editing stations a nuisance. Do you accept and deploy pull requests at the moment?

**Comment by segler-alex** [comment]
i look at every pull request. if it does not break anything, i will merge it :)
help is always greatly appreciated!!

**Comment by indr** [comment]
I also had a look into the client-side part of this issue. I'm willing to make changes so that

1. The modal dialog shows a generic error message and logs it to the browsers console, and
2. The modal dialog is dismissable in case of an error

But before I do anything: Are there any plans to use a (lightweight) html/css(/js) framework @segler-alex ?

**Comment by indr** [comment]
I also had a look into the client-side part of this issue. I'm willing to make changes so that

1. The modal dialog shows a generic error message and logs it to the browsers console, and
2. The modal dialog is dismissable in case of an error

@segler-alex Shall I employ the default bootstrap modal dialog?

**Comment by segler-alex** [comment]
a modal dialog would be just fine
